### ISSUE TITLE
Doesn't work with existing project using @vue/cli-plugin-unit-jest

### ISSUE THREAD

**Issue by Sti2nd** [kaizendorks/vue-cli-plugin-jest-puppeteer#4]
I just installed @vue/cli-plugin-unit-jest and then found vue-cli-plugin-jest-puppeteer. I believed they would work together, but they don't. Might be because this package updates babel-jest to 24 while @vue/cli-plugin-unit-jest installs babel-jest 23?

**Comment by DaniJG** [comment]
Nice catch! The vue-cli-plugin-unit-jest still uses jest 23, so I need to pin the version of jest-puppeteer as 3.9.0 instead of installing the latest one.

**Comment by DaniJG** [comment]
Published version `0.1.3`
